export const actionTypes = {
    SET_PRODUCTS:'SET_PRODUCTS',
    SELECTED_PRODUCTS:'SELECTED_PRODUCTS',
    REMOVE_SELECTED_PRODUCTS:'REMOVE_SELECTED_PRODUCTS',
    ADD_TO_CART:'ADD_TO_CART'
}
export const adminActionTypes = {
    ADD_PRODUCTS:'ADD_PRODUCTS',
}